## Project Information
site_name: Data Open Source
site_url: https://bot-netizen.github.io/khattra-ca/
site_description: Personal Technical Blog

## Repository
#repo_name: khattra-ca 
#repo_url: https://github.com/bot-netizen/khattra-ca
#edit_uri: ''  #disables edit button

# Copyright
copyright: 2023 @DataOpenSource

## Social Media
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://medium.com/@Iqbalkhattra85
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Iqbalkhattra85
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/iqbalsinghkhattra/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bot-netizen
    - icon: fontawesome/solid/envelope
      link: mailto:iqbalkhattra85@gmail.com
  generator: false



theme:
  name: material
  palette:
    primary: green
  custom_dir: docs/theme_override/
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - toc.integrate
    - content.code.copy
  icon:
    logo: dos-hq-logo
  plugins:
    - social:
      cards_font: Roboto
      cards_color:
          fill: "#0FF1CE" 
          text: "#FFFFFF"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true   
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg